/* Auto generated by make_method_table.rb */
#include "_autogen_builtin_symbol.h"

/*===== Range class =====*/
static const mrbc_sym method_symbols_Range[] = {
  MRBC_SYM(EQ_EQ_EQ),
  MRBC_SYM(exclude_end_Q),
  MRBC_SYM(first),
#if MRBC_USE_STRING
  MRBC_SYM(inspect),
#endif
  MRBC_SYM(last),
#if MRBC_USE_STRING
  MRBC_SYM(to_s),
#endif
};

static const mrbc_func_t method_functions_Range[] = {
  c_range_equal3,
  c_range_exclude_end,
  c_range_first,
#if MRBC_USE_STRING
  c_range_inspect,
#endif
  c_range_last,
#if MRBC_USE_STRING
  c_range_inspect,
#endif
};

struct RBuiltinClass mrbc_class_Range = {
  .sym_id = MRBC_SYM(Range),
  .num_builtin_method = sizeof(method_symbols_Range) / sizeof(mrbc_sym),
  .super = MRBC_CLASS(Object),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "Range",
#endif
  .method_symbols = method_symbols_Range,
  .method_functions = method_functions_Range,
};
