/* Auto generated by make_method_table.rb */
#include "_autogen_builtin_symbol.h"

/*===== Exception class =====*/
static const mrbc_sym method_symbols_Exception[] = {
  MRBC_SYM(message),
  MRBC_SYM(new),
};

static const mrbc_func_t method_functions_Exception[] = {
  c_exception_message,
  c_exception_new,
};

struct RBuiltinClass mrbc_class_Exception = {
  .sym_id = MRBC_SYM(Exception),
  .num_builtin_method = sizeof(method_symbols_Exception) / sizeof(mrbc_sym),
  .super = MRBC_CLASS(Object),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "Exception",
#endif
  .method_symbols = method_symbols_Exception,
  .method_functions = method_functions_Exception,
};

/*===== NoMemoryError class =====*/
struct RClass mrbc_class_NoMemoryError = {
  .sym_id = MRBC_SYM(NoMemoryError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(Exception),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "NoMemoryError",
#endif
};

/*===== NotImplementedError class =====*/
struct RClass mrbc_class_NotImplementedError = {
  .sym_id = MRBC_SYM(NotImplementedError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(Exception),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "NotImplementedError",
#endif
};

/*===== StandardError class =====*/
struct RClass mrbc_class_StandardError = {
  .sym_id = MRBC_SYM(StandardError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(Exception),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "StandardError",
#endif
};

/*===== ArgumentError class =====*/
struct RClass mrbc_class_ArgumentError = {
  .sym_id = MRBC_SYM(ArgumentError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "ArgumentError",
#endif
};

/*===== IndexError class =====*/
struct RClass mrbc_class_IndexError = {
  .sym_id = MRBC_SYM(IndexError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "IndexError",
#endif
};

/*===== NameError class =====*/
struct RClass mrbc_class_NameError = {
  .sym_id = MRBC_SYM(NameError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "NameError",
#endif
};

/*===== NoMethodError class =====*/
struct RClass mrbc_class_NoMethodError = {
  .sym_id = MRBC_SYM(NoMethodError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(NameError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "NoMethodError",
#endif
};

/*===== RangeError class =====*/
struct RClass mrbc_class_RangeError = {
  .sym_id = MRBC_SYM(RangeError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "RangeError",
#endif
};

/*===== RuntimeError class =====*/
struct RClass mrbc_class_RuntimeError = {
  .sym_id = MRBC_SYM(RuntimeError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "RuntimeError",
#endif
};

/*===== TypeError class =====*/
struct RClass mrbc_class_TypeError = {
  .sym_id = MRBC_SYM(TypeError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "TypeError",
#endif
};

/*===== ZeroDivisionError class =====*/
struct RClass mrbc_class_ZeroDivisionError = {
  .sym_id = MRBC_SYM(ZeroDivisionError),
  .num_builtin_method = 0,
  .super = MRBC_CLASS(StandardError),
  .method_link = 0,
#if defined(MRBC_DEBUG)
  .name = "ZeroDivisionError",
#endif
};
